name: Build & Deploy

on:
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP (Workload Identity)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/14240076180/locations/global/workloadIdentityPools/github-wif-dev/providers/github
          service_account: github-ci-gcs-writer@gcp-dummy-483112.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker login to Artifact Registry
        run: |
          gcloud auth print-access-token \
            | docker login -u oauth2accesstoken --password-stdin https://europe-west1-docker.pkg.dev

      - name: Build & Push Image
        run: |
          IMAGE=europe-west1-docker.pkg.dev/gcp-dummy-483112/gcp-demo/gcs-writer:${{ github.sha }}
          docker build --no-cache -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy Image to Cloud Run Job
        run: |
          gcloud run jobs update gcs-writer-job \
            --region=europe-west1 \
            --image=${{ env.IMAGE }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Apply
        run: |
          bash ./ci/deploy.sh dev apply


