name: Build & Deploy

on:
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP (Workload Identity)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/14240076180/locations/global/workloadIdentityPools/github-wif-dev/providers/github
          service_account: github-ci-gcs-writer@gcp-dummy-483112.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build & Push Image
        run: |
          IMAGE=europe-west1-docker.pkg.dev/gcp-dummy-483112/gcp-demo/gcs-writer:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Terraform Apply (dev)
        run: ./ci/deploy.sh dev apply
